# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Build
      run: go build -v ./...
  
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
        
    - name: Checkout Source 
      uses: actions/checkout@v3
    
    - name: Create Config file with Secret
      run: |
        cp config/config.json.example config/config.json
        jq '.VirusTotalApiKey = "TESTAPI"' config/config.json > config/config.json
        echo "$(cat config/config.json)"

    - name: Get config path
      run: | 
        echo "BASICGOPOT_CONFIG_FILE=$(pwd)/config/config.json" >> $GITHUB_ENV

    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      
